### PR TITLE
Adds rubocop checks and fixes the code to pass them

### PR DESCRIPTION
**Pull request by luisdavim**
- Added .rubocop.yml
- Fixed all rubocop offences
- Added Yardoc and Rubocop tasks to the Rakefile

### CODE REVIEW

**Comment by stevenviola** [comment]
Thanks for cleaning this up. I'll try to get travis setup to make the PR run Rubocop automatically.

Manually testing these changes, when starting up sensu server, I get the following error with the changes in this commit:

```
{"timestamp":"2017-05-08T22:18:19.580011+0000","level":"info","message":"InfluxDB history extension initialiazed using ://: - Defaults : db= precision="}
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-0.0.1/lib/sensu/extensions/influxdb.rb:79:in `stop': undefined method `flush_buffer' for nil:NilClass (NoMethodError)
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extension-1.5.1/lib/sensu/extension.rb:22:in `block in initialize'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:199:in `ensure in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:205:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:33:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/exe/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:22:in `load'
	from /opt/sensu/bin/sensu-server:22:in `<main>'
```

I'm not sure why `flush_buffer` would be undefined in the InfluxDB extension and not in the History extension, but if we can get that sorted out, I can merge this PR.

Ideally, we could have RSpec load up the extension and verify it sends the event properly. I attempted implementing this but couldn't get it to work, but perhaps we can revisit it.

**Comment by luisdavim** [comment]
Oh, I'll take a look at this tomorrow first thing in the morning. (I'm in Dublin time zone)

**Comment by luisdavim** [comment]
Ok, I took a really quick look and it looks like `require 'sensu/extensions/influxdb/influx_relay'
` was missing in the InfluxDB extension and not in the History extension. I don't have a way to test it at this moment, if you can, please test it and let me know.

**Comment by stevenviola** [comment]
I've updated my previous comment to include a line from the history extension, which indicates the settings weren't loaded properly, because it's omitting the host and protocol. The `flush_buffer ` error might be a red herring, and I think is just happening because sensu is shutting down before the relay class is initialized.

In investigating the missing settings, I think the `parse_settings` and `parse_event` statements are not returning the intended object back. Adding back the `return` lines to these statements seems to fix it for me, and doesn't trigger any rubocop offenses. In the `parse_settings` function, I think what's happening is the `settings['scheme'] ||= 'sensu'` is the last evaluated expression, so the return of that function is just `sensu`, and not the settings object.

**Comment by luisdavim** [comment]
You were right, addiing the retun statements in the right place fixes the issue and doesn't break Rubocop.
I've updated the PR and everything should be fixed now.

**Comment by luisdavim** [comment]
Hi @stevenviola, did you had a chance to test this, it has been working for us with no issues so far.
We are also working on a new branch that adds a feature to use templates to mutate the metric name into tags, field name and measurement name. It works in a similar way to the InfluxDB Graphite input plugin templates and it's close to be ready to be merged to master.

**Comment by stevenviola** [comment]
Hey @luisdavim. I've been testing this out, but it seems the influxdb metrics part isn't sending metrics when I update. The odd thing is there's nothing in the logs that indicate an issue, and I see the correct influx server & port being set upon boot in the logs, but no metrics are coming through on the other end.

The history part is working, and those metrics are coming through, so I _think_ it's something in `influxdb.rb`. Are you using influxdb.rb, or are you loading it by putting the ruby script in the Sensu config directory? Maybe my config has something yours doesn't and that's causing the issue. My config is as follows:

```
{
  "influxdb": {
    "database": "metrics",
    "host": "<FQDN>",
    "port": 7076,
    "use_ssl": false,
    "strip_metric": "host",
    "tags": {
      "region": "<REGION>"
    }
  }
}
```

I'll take a look at this tomorrow and debug to figure out if it's an issue with my setup or what.

**Comment by luisdavim** [comment]
I think I got it, you are using `"strip_metric": "host"` and I'm not and that calls `slice_host` and I think that `slice` always returns a string but  'slice!' returns `nil` if it "has nothing to do". I'll confirm this and get back to you.

**Comment by luisdavim** [comment]
This should be fixed now. Sorry about that.

**Review by stevenviola — CHANGES_REQUESTED** [review]
What's the need to `downcase` when slicing the host? It's perfectly valid to have measurements with that are camel case, and a lot of the sensu-plugins which provide metrics do this. Doing this will create lots of duplicate measurements after updating, require updating any graphs, and will not match the output of the metrics from any scripts.

I suggest we keep the existing functionality and return the value of slice after doing the `.slice!`

**Comment by luisdavim** [comment]
I get your point. The problem is rubocop (wrongly) complains about `Redundant return detected`. 
I'm thinking of using `scrub`, it should fix the issue without being intrusive.

**Comment by luisdavim** [comment]
I've reported this as an issue in rubocop: https://github.com/bbatsov/rubocop/issues/4386

**Comment by stevenviola** [comment]
Yeah, I'm seeing the Rubocop error as well when I change it to `return slice`. Running `rubocop -a lib/sensu/extensions/influxdb.rb` though provides the following change, which fixes the complaint on subsequent runs:

```
@@ -118,6 +118,7 @@ module Sensu
           slice.slice!(char1)
         end
         slice.slice!('.') if slice.chars.first == '.'
+        slice
       end

       def logger
```

Perhaps we should just leave the sliced measurements alone, rather than find a string function which does a noop in most cases.

**Comment by luisdavim** [comment]
Ok, I've updated the PR.

**Comment by stevenviola** [comment]
Awesome, thanks a lot. I've merged this and bumped the version to 0.0.2. I also added Travis CI in the hopes we can have good Rspec tests which will make these PRs go smoother

**Comment by luisdavim** [comment]
Cool. I'll rebase my templates branch and will probably create a new PR soon. 

Thanks.

**Pull request merged**
